service:
  seanime:

  torrent:

#  gluetun:
#    image: qmcgaw/gluetun
#    cap_add:
#      - NET_ADMIN
#    devices:
#      - /dev/net/tun:/dev/net/tun
#    ports:
#      - 8888:8888/tcp # HTTP proxy
#      - 8388:8388/tcp # Shadowsocks
#      - 8388:8388/udp # Shadowsocks
#    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
#      - VPN_SERVICE_PROVIDER=