app = "seanime"  # The name of your app on Fly.io

# Build section to tell Fly.io to build using your Dockerfile
[build]
  # Point to your Dockerfile (this assumes it's in the root directory)
  dockerfile = "Dockerfile"

# Deployment section
[[services]]
  http_checks = []
  internal_port = 8080  # The internal port where your app listens, change if needed
  protocol = "tcp"
  regions = ["ams", "ewr", "sfo"]  # Specify regions you want to deploy to (example: Amsterdam, New York, San Francisco)

  [[services.ports]]
    port = "80"  # Expose app on port 80
    handlers = ["http"]  # Use HTTP handler
