# fly.toml file
app = "seanime"  # Your Fly.io app name

[build]
  # This should point to the correct location of the Dockerfile
  dockerfile = "Dockerfile"  # Ensure the Dockerfile is named "Dockerfile" and is in the root directory

[env]
  PORT = "43000"  # This is the port your app will listen on

[[services]]
  internal_port = 43000  # Internal port your app listens to
  protocol = "tcp"

  # Expose your app to the outside world
  [services.ports]
    port = 80
    handlers = ["http"]

  # Enable health checks
  [services.tcp_checks]
    grace_period = "10s"
    interval = "10s"
    retries = 3
